# Generated by Django 2.1.7 on 2019-11-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20191112_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_created_date',
            new_name='entry_date',
        ),
    ]
