# Generated by Django 2.1.7 on 2019-12-17 16:47

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20191112_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=mdeditor.fields.MDTextField(default=''),
        ),
    ]
